CREATE OR REPLACE TRIGGER PROTECT_DELETE
    BEFORE DELETE
    ON TAKES
    FOR EACH ROW
    WHEN ( OLD.YEAR = 2009 AND OLD.SEMESTER = 'Fall' )
DECLARE
    XCEP EXCEPTION ;
    PRAGMA EXCEPTION_INIT ( XCEP,-20001 );
BEGIN
    DBMS_OUTPUT.PUT_LINE('YEAR 2009 SEMESTER FALL CANT BE DELETED');
    RAISE XCEP;
END;

/

/*
OUTPUT

Trigger created.

DELETE FROM TAKES WHERE YEAR=2009 AND SEMESTER='Fall';
YEAR 2009 SEMESTER FALL CANT BE DELETED
DELETE FROM TAKES WHERE YEAR=2009 AND SEMESTER='Fall'
            *
ERROR at line 1:
ORA-20001:
ORA-06512: at "R569.PROTECT_DELETE", line 6
ORA-04088: error during execution of trigger 'R569.PROTECT_DELETE'

*/